name: Docker Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker image build
      run: docker build . --file Dockerfile --tag redundant_bus_csp:$(date +%s)
