name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup packages on Linux
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get update
        sudo apt-get install libzmq3-dev libsocketcan-dev socat iproute2 libboost-program-options-dev
        sudo apt-get install linux-modules-extra-$(uname -r)

    - name: Submodules Init
      run: |
        git submodule init
        git submodule update

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCSP_USE_RTABLE=ON -DCSP_BUFFER_COUNT=50 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Setup vcan ifaces
      run: ./scripts/virt_net_conf.sh

    - name: Run redundant bus test
      run: ./scripts/redundant_bus_test.sh 10

    - name: Run multiple servers test
      run: ./scripts/multiple_servers_test.sh 10
